FROM afelder/proxygen:v2020.07.13.00-builder

LABEL maintainer="armin.felder@osalliance.com"

RUN apt-get update && apt-get --yes install libjsoncpp-dev libcurl4-openssl-dev libboost-all-dev cmake build-essential&& apt-get clean

