//
// Created by armin on 16.11.17.
//

#ifndef ROCKETCHATMOBILEPUSHGATEWAY_APPLEPUSHMODEL_H
#define ROCKETCHATMOBILEPUSHGATEWAY_APPLEPUSHMODEL_H


class ApplePushModel {

};


#endif //ROCKETCHATMOBILEPUSHGATEWAY_APPLEPUSHMODEL_H
